export interface IAAQuestion {
  id: string;
  textDe: string;
  textEn: string;
  hintDe?: string;
  hintEn?: string;
}

export interface IAACategory {
  id: string;
  titleDe: string;
  titleEn: string;
  questions: IAAQuestion[];
}

export const iaaCategories: IAACategory[] = [
  {
    id: "stuhl",
    titleDe: "Stuhlverhalten",
    titleEn: "Bowel Habits",
    questions: [
      { id: "1.1", textDe: "Verstopfung?", textEn: "Constipation?", hintDe: "Als Verstopfung wird jede Verzögerung und Unregelmäßigkeit im Stuhlgang verstanden.", hintEn: "Constipation refers to any delay or irregularity in bowel movements." },
      { id: "1.1.1", textDe: "Verkrampfter, schwieriger Stuhlgang?", textEn: "Cramped, difficult bowel movements?" },
      { id: "1.1.2", textDe: "Verstopfung besser, wenn Sie sich Zeit nehmen?", textEn: "Constipation better when you take your time?" },
      { id: "1.1.3", textDe: "Bei Bewegung und/oder Trinken Verstopfung besser?", textEn: "Constipation better with exercise and/or drinking?" },
      { id: "1.2.1", textDe: "Ist es fettiger Stuhl? (schwimmt auf)", textEn: "Is it fatty stool? (floats)" },
      { id: "1.2.2", textDe: "Ist es breiiger Stuhl?", textEn: "Is it mushy stool?" },
      { id: "2.1.7", textDe: "Ist es schmieriger Stuhl? (viel Klopapier)", textEn: "Is it greasy stool? (lots of toilet paper)" },
      { id: "1.2.3", textDe: "Stuhl riecht säuerlich?", textEn: "Stool smells sour?" },
      { id: "1.2.4", textDe: "Darmprobleme allgemein? Stressbedingt?", textEn: "General intestinal problems? Stress-related?" },
      { id: "1.2.5", textDe: "Untere Rückenprobleme, die sich nach dem Stuhlgang besser anfühlen?", textEn: "Lower back problems that feel better after bowel movement?" },
      { id: "1.2.6", textDe: "Am Oberbauch rechts Druckgefühl?", textEn: "Pressure feeling in upper right abdomen?" },
      { id: "1.3", textDe: "Stressbedingter Durchfall?", textEn: "Stress-related diarrhea?" },
      { id: "1.3.1", textDe: "Durchfall akut?", textEn: "Acute diarrhea?" },
      { id: "1.3.3", textDe: "Durchfall alternierend mit Verstopfung?", textEn: "Diarrhea alternating with constipation?" },
    ],
  },
  {
    id: "blaehungen",
    titleDe: "Blähungen / Winde",
    titleEn: "Bloating / Flatulence",
    questions: [
      { id: "2.1.1", textDe: "Stressbedingte Blähungen?", textEn: "Stress-related bloating?" },
      { id: "2.1.1.1", textDe: "Blähungen allgemein?", textEn: "General bloating?" },
      { id: "2.1.2", textDe: "Unspezifische Winde/Blähungen im unteren Bauchbereich?", textEn: "Unspecific flatulence/bloating in lower abdomen?" },
      { id: "2.1.3", textDe: "Unspezifische Winde/Blähungen im oberen Bauchbereich?", textEn: "Unspecific flatulence/bloating in upper abdomen?" },
      { id: "2.1.4", textDe: "Gärungsdyspepsie?", textEn: "Fermentation dyspepsia?" },
      { id: "2.1.4.1", textDe: "Gärungen im Bauch bei Süßigkeiten? Bedarf nach Süßem?", textEn: "Fermentation with sweets? Craving for sweets?" },
      { id: "2.1.5", textDe: "Winde riechen nach faulen Eiern?", textEn: "Flatulence smells like rotten eggs?" },
      { id: "2.1.6", textDe: "Druck im Oberbauch? Luft im Oberbauch?", textEn: "Pressure in upper abdomen? Air in upper abdomen?" },
    ],
  },
  {
    id: "nahrung",
    titleDe: "Nahrungsmittelunverträglichkeiten",
    titleEn: "Food Intolerances",
    questions: [
      { id: "2.2", textDe: "Allgemeine Nahrungsmittelunverträglichkeiten?", textEn: "General food intolerances?" },
      { id: "2.2.1", textDe: "Zucker-/Obst-Unverträglichkeit oder Süßigkeitsbedarf?", textEn: "Sugar/fruit intolerance or craving for sweets?" },
      { id: "2.2.2", textDe: "Gefühl von Überforderung von Magen/Darm?", textEn: "Feeling of overwhelmed stomach/intestines?" },
      { id: "2.2.2.1", textDe: "Ernähren Sie sich eher ungesund? (Kantine, Fastfood, Fertiggerichte)", textEn: "Do you eat rather unhealthily? (canteen, fast food, ready meals)" },
      { id: "2.2.3", textDe: "Fettiges Essen und Öle nicht gut verträglich?", textEn: "Fatty food and oils not well tolerated?" },
      { id: "2.2.4", textDe: "Tierische Eiweißprodukte schlecht verträglich? Milchprodukt-/Ei-Unverträglichkeiten?", textEn: "Animal protein products poorly tolerated? Dairy/egg intolerances?" },
      { id: "2.2.5", textDe: "Ungutes Gefühl im Oberbauch?", textEn: "Uncomfortable feeling in upper abdomen?" },
      { id: "2.4", textDe: "Undefinierbarer Bauchdruck bis -krämpfe?", textEn: "Undefinable abdominal pressure to cramps?" },
      { id: "2.5.6", textDe: "Haben oder hatten Sie jemals Magen- oder Darmgeschwüre?", textEn: "Have you ever had stomach or intestinal ulcers?" },
      { id: "2.7", textDe: "Haben oder hatten Sie jemals Hämorrhoiden?", textEn: "Have you ever had hemorrhoids?" },
      { id: "2.7.2", textDe: "Hatten Sie jemals eine Lebensmittelvergiftung?", textEn: "Have you ever had food poisoning?" },
    ],
  },
  {
    id: "appetit",
    titleDe: "Appetit / Magen",
    titleEn: "Appetite / Stomach",
    questions: [
      { id: "3.1", textDe: "Allgemeine Magenbeschwerden?", textEn: "General stomach complaints?" },
      { id: "3.1.3", textDe: "Magenbeschwerden mit Luft und Oberbauchdruck nach dem Essen?", textEn: "Stomach complaints with air and upper abdominal pressure after eating?" },
      { id: "3.1.4.1", textDe: "Magenbeschwerden mit Oberbauchdruck nach dem Essen stressbedingt?", textEn: "Stress-related stomach complaints with pressure after eating?" },
      { id: "3.1.6", textDe: "Magenreizung mit Sodbrennen?", textEn: "Stomach irritation with heartburn?" },
      { id: "3.1.7", textDe: "Magenbeschwerden bei Stress, Nervosität, Hunger?", textEn: "Stomach complaints with stress, nervousness, hunger?" },
      { id: "3.2", textDe: "Magenübersäuerung / Brechreiz / Aufstoßen / Sodbrennen?", textEn: "Stomach hyperacidity / nausea / belching / heartburn?" },
      { id: "3.2.6", textDe: "Aufstoßen sauer allgemein?", textEn: "General sour belching?" },
      { id: "3.2.7", textDe: "Magenschmerzen mit Brennen?", textEn: "Stomach pain with burning?" },
      { id: "3.2.8", textDe: "Wurde jemals Helicobacter festgestellt?", textEn: "Was Helicobacter ever diagnosed?" },
      { id: "3.2.11", textDe: "Sodbrennen bei Stress?", textEn: "Heartburn with stress?" },
      { id: "3.3.1", textDe: "Langes Verweilen der Nahrung im Magen, Kloßgefühl?", textEn: "Food staying long in stomach, lump feeling?" },
      { id: "3.4", textDe: "Appetitlosigkeit?", textEn: "Loss of appetite?" },
      { id: "3.4.1", textDe: "Appetitlosigkeit stressbedingt?", textEn: "Stress-related loss of appetite?" },
      { id: "3.4.2", textDe: "Appetitlosigkeit mit kaltem Bauchgefühl?", textEn: "Loss of appetite with cold belly feeling?" },
    ],
  },
  {
    id: "allergien",
    titleDe: "Allergien",
    titleEn: "Allergies",
    questions: [
      { id: "4.1", textDe: "Allgemeine Allergien?", textEn: "General allergies?" },
      { id: "4.2", textDe: "Heuschnupfen?", textEn: "Hay fever?" },
      { id: "4.3", textDe: "Allergien auf tierische Eiweiße (Milchprodukte, Eier, Fleisch)?", textEn: "Allergies to animal proteins (dairy, eggs, meat)?" },
      { id: "4.3.3", textDe: "Allergien auf Antibiotika, Penicillin, Medikamente?", textEn: "Allergies to antibiotics, penicillin, medications?" },
      { id: "4.3.4", textDe: "Allergien auf Konservierungsmittel?", textEn: "Allergies to preservatives?" },
    ],
  },
  {
    id: "niere",
    titleDe: "Durst / Niere / Blase",
    titleEn: "Thirst / Kidneys / Bladder",
    questions: [
      { id: "5.1", textDe: "Fehlendes Durstgefühl?", textEn: "Lack of thirst?" },
      { id: "5.2", textDe: "Öfters Blasenreizungen und kalte Füße?", textEn: "Frequent bladder irritation and cold feet?" },
      { id: "5.2.1.1", textDe: "Blasenreizungen und dicke Beine, Sockenabdruck?", textEn: "Bladder irritation and swollen legs, sock marks?" },
      { id: "5.2.2", textDe: "Müssen Sie oft dringend Wasser lassen?", textEn: "Do you often need to urinate urgently?" },
      { id: "5.3", textDe: "Blaseninfekte nach Geschlechtsverkehr?", textEn: "Bladder infections after intercourse?" },
      { id: "5.5", textDe: "Störungen beim Wasserlassen, auch stressbedingt?", textEn: "Difficulties urinating, also stress-related?" },
      { id: "5.6", textDe: "Müssen Sie nachts oft Wasserlassen?", textEn: "Do you need to urinate often at night?" },
      { id: "5.7", textDe: "Schwierigkeiten, Wasser zu halten seit dem Gebären?", textEn: "Difficulty holding urine since childbirth?" },
      { id: "5.8", textDe: "Bettnässen bei Kindern?", textEn: "Bedwetting in children?" },
      { id: "5.10", textDe: "Brennen beim Wasserlassen?", textEn: "Burning when urinating?" },
      { id: "5.11", textDe: "Hatten Sie jemals Nierenprobleme?", textEn: "Have you ever had kidney problems?" },
      { id: "5.12", textDe: "Haben Sie gerade akute Nierenprobleme?", textEn: "Do you currently have acute kidney problems?" },
    ],
  },
  {
    id: "schlaf",
    titleDe: "Schlaf",
    titleEn: "Sleep",
    questions: [
      { id: "6.1", textDe: "Einschlafstörungen?", textEn: "Difficulty falling asleep?" },
      { id: "6.2", textDe: "Wachen Sie nachts regelmäßig auf?", textEn: "Do you wake up regularly at night?" },
      { id: "6.2.1", textDe: "Wenn ja, um welche Uhrzeit ungefähr?", textEn: "If yes, at approximately what time?" },
    ],
  },
  {
    id: "atmung",
    titleDe: "Bewegung / Atmung",
    titleEn: "Movement / Breathing",
    questions: [
      { id: "7.1", textDe: "Wie schlimm ist Ihr Bewegungsmangel?", textEn: "How bad is your lack of exercise?" },
      { id: "7.1.1", textDe: "Atembeschwerden zusammen mit Herzbeschwerden?", textEn: "Breathing difficulties together with heart problems?" },
      { id: "7.1.3", textDe: "Atmen Sie sehr flach?", textEn: "Do you breathe very shallowly?" },
      { id: "7.1.4", textDe: "Atmen Sie schwer und flach bei Stress?", textEn: "Do you breathe heavily and shallowly under stress?" },
      { id: "7.2.1", textDe: "Sind Sie kurzatmig? (beim Treppensteigen)", textEn: "Are you short of breath? (climbing stairs)" },
      { id: "7.3", textDe: "Periodische Atemnot?", textEn: "Periodic shortness of breath?" },
      { id: "7.4", textDe: "Schweres Atmen mit niedrigem Blutdruck?", textEn: "Heavy breathing with low blood pressure?" },
      { id: "7.6", textDe: "Verschleimte Bronchien?", textEn: "Congested bronchi?" },
      { id: "7.7", textDe: "Husten?", textEn: "Cough?" },
      { id: "7.7.1", textDe: "Husten mit viel Schleim?", textEn: "Cough with lots of mucus?" },
      { id: "7.7.2", textDe: "Oft Hustenreiz?", textEn: "Frequent coughing urge?" },
      { id: "7.7.4", textDe: "Gerade akuter Husten?", textEn: "Currently acute cough?" },
      { id: "7.8", textDe: "Chronische Bronchitis?", textEn: "Chronic bronchitis?" },
      { id: "7.9", textDe: "Klebrig weißer Auswurf?", textEn: "Sticky white sputum?" },
      { id: "7.10", textDe: "Akute Lungenentzündung?", textEn: "Acute pneumonia?" },
      { id: "7.11", textDe: "Asthma?", textEn: "Asthma?" },
    ],
  },
  {
    id: "haut",
    titleDe: "Haut",
    titleEn: "Skin",
    questions: [
      { id: "8.1", textDe: "Trockene Haut?", textEn: "Dry skin?" },
      { id: "8.2", textDe: "Leicht gereizte Haut? (öfters Ausschläge)", textEn: "Easily irritated skin? (frequent rashes)" },
      { id: "8.3", textDe: "Gelegentlich Ekzeme, Furunkel?", textEn: "Occasional eczema, boils?" },
      { id: "8.3.4", textDe: "Fettige Haut?", textEn: "Oily skin?" },
      { id: "8.5", textDe: "Bindegewebsschwäche?", textEn: "Connective tissue weakness?" },
      { id: "8.5.3", textDe: "Bindegewebsschwäche mit Besenreisern?", textEn: "Connective tissue weakness with spider veins?" },
      { id: "8.5.4", textDe: "Wassereinlagerungen im Gewebe?", textEn: "Water retention in tissue?" },
    ],
  },
  {
    id: "bewegungsapparat",
    titleDe: "Bewegungsapparat",
    titleEn: "Musculoskeletal System",
    questions: [
      { id: "10.1", textDe: "Allgemeine Gelenkschmerzen?", textEn: "General joint pain?" },
      { id: "10.1.1", textDe: "Leistenschmerzen?", textEn: "Groin pain?" },
      { id: "10.1.2", textDe: "Nackenschmerzen?", textEn: "Neck pain?" },
      { id: "10.1.2.1", textDe: "Nackenschmerzen einseitig?", textEn: "One-sided neck pain?" },
      { id: "10.1.3", textDe: "Schmerzen in den Flanken?", textEn: "Pain in the flanks?" },
      { id: "10.1.4", textDe: "Schmerzen in den oberen Extremitäten?", textEn: "Pain in upper extremities?" },
      { id: "10.1.5", textDe: "Schmerzen im Rippenbereich?", textEn: "Pain in rib area?" },
      { id: "10.1.6", textDe: "Schmerzen im Schulterblatt?", textEn: "Pain in shoulder blade?" },
      { id: "10.2", textDe: "Krampfartige Schmerzen?", textEn: "Cramping pain?" },
      { id: "10.3", textDe: "Muskelschmerzen?", textEn: "Muscle pain?" },
      { id: "10.4", textDe: "Rheumatische Schmerzen in Weichteilen?", textEn: "Rheumatic pain in soft tissues?" },
      { id: "10.6", textDe: "Wadenkrämpfe?", textEn: "Calf cramps?" },
      { id: "10.7", textDe: "Allgemeine Wirbelsäulenschmerzen?", textEn: "General spine pain?" },
      { id: "10.7.3", textDe: "Wirbelsäulenschmerzen eines Abschnittes?", textEn: "Spine pain in one section?" },
      { id: "10.7.4", textDe: "Bandscheibenabnutzung mit Schmerzen?", textEn: "Disc wear with pain?" },
      { id: "10.8", textDe: "Nacken blockiert?", textEn: "Neck feels blocked?" },
      { id: "10.9", textDe: "Steißbein/Kreuzbein blockiert?", textEn: "Tailbone/sacrum feels blocked?" },
      { id: "10.10", textDe: "Hüftbeschwerden / Hüftarthrose?", textEn: "Hip complaints / hip arthritis?" },
      { id: "10.11", textDe: "Fuß- oder Kniebeschwerden?", textEn: "Foot or knee complaints?" },
      { id: "10.11.1.1", textDe: "Fußgelenkprobleme chronisch?", textEn: "Chronic ankle problems?" },
      { id: "10.11.1.3", textDe: "Beschwerden im Kniegelenk?", textEn: "Knee joint complaints?" },
      { id: "10.12", textDe: "Beschwerden im Ellbogengelenk?", textEn: "Elbow joint complaints?" },
      { id: "10.13", textDe: "Schultergelenkschmerzen?", textEn: "Shoulder joint pain?" },
      { id: "10.14", textDe: "Handgelenkschmerzen, Karpaltunnelsyndrom?", textEn: "Wrist pain, carpal tunnel syndrome?" },
      { id: "10.14.4", textDe: "Sehnenscheidenentzündung am Handgelenk?", textEn: "Tendinitis at the wrist?" },
      { id: "10.15", textDe: "Kiefergelenkprobleme, Kauprobleme?", textEn: "Jaw joint problems, chewing problems?" },
      { id: "10.17", textDe: "Dupuytren-Kontraktur?", textEn: "Dupuytren's contracture?" },
    ],
  },
  {
    id: "immunsystem",
    titleDe: "Abwehr / Immunsystem",
    titleEn: "Defense / Immune System",
    questions: [
      { id: "11.1", textDe: "Oft erkältet, Schnupfen?", textEn: "Often cold, runny nose?" },
      { id: "11.2.5", textDe: "Ist eine Autoimmuntendenz bekannt?", textEn: "Is an autoimmune tendency known?" },
      { id: "11.3", textDe: "Öfters Grippe?", textEn: "Frequent flu?" },
      { id: "11.4", textDe: "Öfters Fieber?", textEn: "Frequent fever?" },
      { id: "11.4.1.1", textDe: "Fiebrige Entzündung mit Beteiligung des Halsbereichs?", textEn: "Feverish inflammation involving throat area?" },
      { id: "11.5.3", textDe: "Mandelentzündung?", textEn: "Tonsillitis?" },
      { id: "11.5.4", textDe: "Schluckbeschwerden?", textEn: "Difficulty swallowing?" },
      { id: "11.6", textDe: "Nasennebenhöhlenprobleme mit Schnupfen?", textEn: "Sinus problems with cold?" },
      { id: "11.7", textDe: "Nebenhöhlenentzündung?", textEn: "Sinusitis?" },
      { id: "11.8", textDe: "Nase verstopft?", textEn: "Stuffy nose?" },
      { id: "11.9", textDe: "Geruchsverlust?", textEn: "Loss of smell?" },
    ],
  },
  {
    id: "ohren",
    titleDe: "Ohren / Gehör",
    titleEn: "Ears / Hearing",
    questions: [
      { id: "11.10", textDe: "Gehör-/Ohrenprobleme allgemein?", textEn: "General hearing/ear problems?" },
      { id: "11.10.1.1", textDe: "Ohrenschmerzen?", textEn: "Ear pain?" },
      { id: "11.10.2", textDe: "Chronische Ohrenentzündung?", textEn: "Chronic ear infection?" },
      { id: "11.11", textDe: "Schwerhörigkeit?", textEn: "Hearing loss?" },
      { id: "11.11.1", textDe: "Hörsturz?", textEn: "Sudden hearing loss?" },
      { id: "11.11.3", textDe: "Taubheit/Schwerhörigkeit/Gehörstörungen?", textEn: "Deafness/hearing loss/hearing disorders?" },
      { id: "11.11.6", textDe: "Tinnitus?", textEn: "Tinnitus?" },
    ],
  },
  {
    id: "zaehne",
    titleDe: "Zähne",
    titleEn: "Teeth",
    questions: [
      { id: "12.1", textDe: "Diffuse Zahnschmerzen?", textEn: "Diffuse tooth pain?" },
      { id: "12.2", textDe: "Tiefe Zahnprobleme / Zahnherde?", textEn: "Deep dental problems / dental foci?" },
      { id: "12.3", textDe: "Zahnschmerzen?", textEn: "Toothache?" },
      { id: "12.4", textDe: "Zahnlockerungen?", textEn: "Loose teeth?" },
      { id: "12.5", textDe: "Parodontose?", textEn: "Periodontitis?" },
      { id: "12.6", textDe: "Zahnfleischerkrankungen?", textEn: "Gum disease?" },
    ],
  },
  {
    id: "lymphe",
    titleDe: "Lymphe",
    titleEn: "Lymph",
    questions: [
      { id: "13.1", textDe: "Lymphstauungen?", textEn: "Lymph congestion?" },
      { id: "13.1.2", textDe: "Häufiger Seitenstechen?", textEn: "Frequent side stitch?" },
      { id: "13.1.4", textDe: "Lymphödeme?", textEn: "Lymphedema?" },
      { id: "13.1.6", textDe: "Extrem geschwollene Beine?", textEn: "Extremely swollen legs?" },
    ],
  },
  {
    id: "nerven",
    titleDe: "Nervensystem / Kopfschmerzen",
    titleEn: "Nervous System / Headaches",
    questions: [
      { id: "14.1", textDe: "Ziehende Nervenschmerzen?", textEn: "Pulling nerve pain?" },
      { id: "15.1", textDe: "Kopfschmerzen?", textEn: "Headaches?" },
      { id: "15.1.2", textDe: "Nacken-Kopfschmerzen?", textEn: "Neck headaches?" },
      { id: "15.1.3", textDe: "Kopfdruck in der Mitte des Kopfes?", textEn: "Head pressure in the middle?" },
      { id: "15.1.4", textDe: "Kopfdruck im Stirnbereich?", textEn: "Head pressure in forehead area?" },
      { id: "15.1.5", textDe: "Kopfdruck gesamt und Schädelbereich?", textEn: "Overall head and skull pressure?" },
      { id: "15.1.7", textDe: "Hinterkopfschmerzen?", textEn: "Back of head pain?" },
      { id: "15.1.8", textDe: "Kopfschmerzen linksseitig und Scheitelbereich?", textEn: "Left-sided headaches and crown area?" },
    ],
  },
  {
    id: "psyche",
    titleDe: "Psyche / Vitalität",
    titleEn: "Psyche / Vitality",
    questions: [
      { id: "16.1", textDe: "Öfters Aggressionen?", textEn: "Frequent aggression?" },
      { id: "16.1.2", textDe: "Oft gestresst?", textEn: "Often stressed?" },
      { id: "16.2", textDe: "Beklemmungsgefühle?", textEn: "Feelings of oppression?" },
      { id: "16.3", textDe: "Müdigkeit?", textEn: "Fatigue?" },
      { id: "16.3.2", textDe: "Große Müdigkeit?", textEn: "Great fatigue?" },
      { id: "16.4", textDe: "Kraftlosigkeit?", textEn: "Weakness?" },
      { id: "16.5", textDe: "Depressive Verstimmung / Sorgen / Grübeln?", textEn: "Depressive mood / worries / brooding?" },
      { id: "16.5.3", textDe: "Depressive Verstimmung nach Ärger?", textEn: "Depressive mood after anger?" },
      { id: "16.5.4", textDe: "Depressive Verstimmung nach Herzkummer?", textEn: "Depressive mood after heartbreak?" },
      { id: "16.6", textDe: "Häufig emotional blockiert?", textEn: "Frequently emotionally blocked?" },
      { id: "16.7", textDe: "Eindruck eines Energiemangels mit zu wenig Sauerstoff?", textEn: "Impression of energy deficit with too little oxygen?" },
      { id: "16.8", textDe: "Fühlen Sie sich ausgepowert?", textEn: "Do you feel exhausted?" },
      { id: "16.8.1", textDe: "Fehlt es Ihnen an Kraft und Lebensfreude?", textEn: "Do you lack strength and zest for life?" },
      { id: "16.9", textDe: "Neigen Sie leicht zu Frösteln und Frieren?", textEn: "Do you tend to feel chilly and cold easily?" },
    ],
  },
  {
    id: "herz",
    titleDe: "Herz-Kreislauf und Gefäße",
    titleEn: "Cardiovascular System",
    questions: [
      { id: "17.1", textDe: "Blutdruck erhöht?", textEn: "Blood pressure elevated?" },
      { id: "17.2", textDe: "Blutdruck zu niedrig?", textEn: "Blood pressure too low?" },
      { id: "17.2.1", textDe: "Kreislaufschwäche, Schwindel?", textEn: "Circulatory weakness, dizziness?" },
      { id: "17.2.3.1", textDe: "Blutdruckschwankungen?", textEn: "Blood pressure fluctuations?" },
      { id: "17.3", textDe: "Kreislauf unterstützen?", textEn: "Support circulation?" },
      { id: "17.5.2", textDe: "Herzsensationen bei Stress?", textEn: "Heart sensations under stress?" },
      { id: "17.5.2.1", textDe: "Brennen in den Beinen?", textEn: "Burning in the legs?" },
      { id: "17.5.3", textDe: "Herzrasen?", textEn: "Racing heart?" },
      { id: "17.6", textDe: "Brustbeklemmung?", textEn: "Chest tightness?" },
      { id: "17.7", textDe: "Angina Pektoris?", textEn: "Angina pectoris?" },
      { id: "17.8", textDe: "Herzschmerzen?", textEn: "Heart pain?" },
      { id: "17.8.2", textDe: "Herzschmerzen bei Sauerstoffmangel?", textEn: "Heart pain with oxygen deficiency?" },
      { id: "17.8.3", textDe: "Herzschmerzen bei emotionalem Stress?", textEn: "Heart pain with emotional stress?" },
      { id: "17.8.6", textDe: "Herzprobleme durch Luft im Magen?", textEn: "Heart problems from air in stomach?" },
      { id: "17.10", textDe: "Venenschwäche?", textEn: "Venous weakness?" },
      { id: "17.10.3", textDe: "Venenschwäche, Couperose?", textEn: "Venous weakness, couperose?" },
      { id: "17.10.4", textDe: "Krampfadern?", textEn: "Varicose veins?" },
      { id: "17.11", textDe: "Venenentzündung (Phlebitis)?", textEn: "Venous inflammation (phlebitis)?" },
      { id: "17.11.1", textDe: "Venenentzündung schmerzhaft?", textEn: "Painful venous inflammation?" },
    ],
  },
  {
    id: "sucht",
    titleDe: "Sucht / Hormone",
    titleEn: "Addiction / Hormones",
    questions: [
      { id: "18.1", textDe: "Rauchen Sie?", textEn: "Do you smoke?" },
      { id: "18.2", textDe: "Alkohol täglich?", textEn: "Daily alcohol?" },
      { id: "18.3", textDe: "Sonstige Sucht?", textEn: "Other addiction?" },
      { id: "19.3", textDe: "Schilddrüsenregulation (auch Kropf/Struma)?", textEn: "Thyroid regulation (including goiter)?" },
      { id: "19.3.3", textDe: "Schilddrüsen-Probleme allgemein?", textEn: "General thyroid problems?" },
      { id: "19.3.4", textDe: "Schilddrüsenüberfunktion?", textEn: "Hyperthyroidism?" },
      { id: "19.3.5", textDe: "Schilddrüsenunterfunktion/-erschöpfung?", textEn: "Hypothyroidism/thyroid exhaustion?" },
      { id: "19.3.6", textDe: "Thyreoiditis (Schilddrüsenentzündung)?", textEn: "Thyroiditis?" },
      { id: "19.3.7", textDe: "Würgegefühl? (Schilddrüse)", textEn: "Gagging feeling? (thyroid)" },
    ],
  },
  {
    id: "geschlecht",
    titleDe: "Geschlechtsspezifisch",
    titleEn: "Gender-Specific",
    questions: [
      { id: "19.4", textDe: "Genitalbereich schmerzend?", textEn: "Genital area painful?" },
      { id: "19.5", textDe: "Menstruationsbeschwerden mit Krämpfen?", textEn: "Menstrual complaints with cramps?" },
      { id: "19.5.1", textDe: "Menstruation stark?", textEn: "Heavy menstruation?" },
      { id: "19.5.1.5", textDe: "Menstruation, nicht stillbar?", textEn: "Menstruation, unstoppable?" },
      { id: "19.5.2", textDe: "Menstruation, ausbleibend?", textEn: "Missed menstruation?" },
      { id: "19.5.4", textDe: "Menstruationsschmerzen?", textEn: "Menstrual pain?" },
      { id: "19.5.6", textDe: "Scheidenausfluss?", textEn: "Vaginal discharge?" },
      { id: "19.5.7", textDe: "Wechseljahrbeschwerden?", textEn: "Menopausal complaints?" },
      { id: "19.5.8", textDe: "Schwangerschaftsübelkeit?", textEn: "Morning sickness?" },
      { id: "19.6", textDe: "Potenzschwierigkeiten?", textEn: "Potency difficulties?" },
      { id: "19.6.3", textDe: "Impotenz?", textEn: "Impotence?" },
      { id: "19.6.4", textDe: "Samenverlust?", textEn: "Semen loss?" },
    ],
  },
  {
    id: "augen",
    titleDe: "Augen",
    titleEn: "Eyes",
    questions: [
      { id: "20.1", textDe: "Augenüberanstrengung?", textEn: "Eye strain?" },
      { id: "20.1.1", textDe: "Kurz- und Weitsichtigkeit?", textEn: "Near and farsightedness?" },
      { id: "20.1.2", textDe: "Tränenfluss?", textEn: "Tearing?" },
      { id: "20.2", textDe: "Augenerkrankungen?", textEn: "Eye diseases?" },
      { id: "20.3", textDe: "Augenschmerzen, Rötung, entzündlich?", textEn: "Eye pain, redness, inflammatory?" },
      { id: "20.3.3", textDe: "Bindehautentzündung stressbedingt?", textEn: "Stress-related conjunctivitis?" },
      { id: "20.4", textDe: "Augenschmerz mit Schleierbildung?", textEn: "Eye pain with blurring?" },
      { id: "20.6", textDe: "Augeninnendruck erhöht?", textEn: "Elevated intraocular pressure?" },
      { id: "20.6.1", textDe: "Druck auf den Augen?", textEn: "Pressure on the eyes?" },
      { id: "20.7", textDe: "Sehstörungen / Schwindel?", textEn: "Visual disturbances / dizziness?" },
      { id: "20.9", textDe: "Grauer Star (Katarakt) Frühstadium?", textEn: "Cataract early stage?" },
      { id: "20.10", textDe: "Hornhaut Dystrophie / Degeneration?", textEn: "Corneal dystrophy / degeneration?" },
      { id: "20.11", textDe: "Nachtblindheit?", textEn: "Night blindness?" },
      { id: "20.12", textDe: "Farbenblindheit?", textEn: "Color blindness?" },
    ],
  },
  {
    id: "blockaden",
    titleDe: "Blockaden",
    titleEn: "Blockages",
    questions: [
      { id: "21.7.1", textDe: "Nehmen Sie chemische Medikamente / Opiate?", textEn: "Do you take chemical medications / opiates?" },
      { id: "21.7.3", textDe: "Hatten Sie Operationen? (Blockade durch Narkosemittel)", textEn: "Have you had surgeries? (blockage from anesthetics)" },
      { id: "22.1", textDe: "Cellulite?", textEn: "Cellulite?" },
    ],
  },
];

// Therapist-only section
export const therapistCategories: IAACategory[] = [
  {
    id: "therapeut",
    titleDe: "Therapeut-Bereich (Entgiftung & Ausleitung)",
    titleEn: "Therapist Section (Detoxification & Drainage)",
    questions: [
      { id: "21.1", textDe: "Darmentgiftung", textEn: "Intestinal detoxification" },
      { id: "21.2", textDe: "Hautentgiftung Übersäuerung", textEn: "Skin detox hyperacidity" },
      { id: "21.3", textDe: "Toxinausleitung", textEn: "Toxin drainage" },
      { id: "21.4", textDe: "Leberentgiftung", textEn: "Liver detoxification" },
      { id: "21.5", textDe: "Leberentgiftung durch Lymphanregung", textEn: "Liver detox through lymph stimulation" },
      { id: "21.5.1", textDe: "Entgiftung über Lunge", textEn: "Detox via lungs" },
      { id: "21.6", textDe: "Nierenentgiftung", textEn: "Kidney detoxification" },
      { id: "21.7", textDe: "Entgiftung wegen Chemikalien", textEn: "Detox due to chemicals" },
      { id: "21.7.4", textDe: "Impfschäden", textEn: "Vaccine damage" },
      { id: "21.7.5", textDe: "Strahlenbelastung", textEn: "Radiation exposure" },
    ],
  },
];
