project_id = "jmebqjadlpltnqawoipb"

[functions.request-verification-code]
verify_jwt = false

[functions.verify-code]
verify_jwt = false

[functions.submit-anamnesis]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.generate-icd10]
verify_jwt = false

[functions.send-icd10-report]
verify_jwt = false

[functions.resend-submission]
verify_jwt = false

[functions.get-patients]
verify_jwt = false
